FROM alpine:3.7
LABEL maintainer="Quantworks Inc."


ARG AIRFLOW_HOME=/usr/local/airflow
WORKDIR /usr/local/airflow
COPY ./script/install.sh .
COPY ./script/requirements.txt .

RUN apk update && \
    apk add --no-cache curl bash python3-dev && \
    apk add --no-cache --virtual .build-deps g++ libxml2-dev linux-headers && \
    apk add --no-cache --virtual .build-deps libxslt-dev postgresql-dev && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    apk add --no-cache postgresql-client && \
    ./install.sh && \
    apk del .build-deps

COPY ./airflow.cfg .
COPY ./script/entrypoint.sh .

ENV AIRFLOW_HOME ${AIRFLOW_HOME}

CMD ["/usr/local/airflow/entrypoint.sh"]